default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ilkertoklu
  password:
  timeout: 5000

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
